# Generated by Django 3.0.5 on 2020-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.CharField(default='test', max_length=254),
            preserve_default=False,
        ),
    ]
